#!/bin/bash

SERVICE=obelix-appengine
S3BUCKET="s3://build/deployment"

if [ -z $ANS_VERSION ]; then
    ANS_VERSION=latest-stable
fi
if [ -z $VERSION ]; then
    VERSION=latest-stable
fi

aws s3 cp ${S3BUCKET}/${SERVICE}.sh obelix-appengine.sh
chmod +x obelix-appengine.sh
./obelix-appengine.sh $ANS_VERSION $VERSION